//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandaab.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Locale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Locale() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sandaab.Core.Properties.Locale", typeof(Locale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Zugriff auf das Gerät {0} wurde verwehrt. ähnelt.
        /// </summary>
        public static string AccessDeniedMessage {
            get {
                return ResourceManager.GetString("AccessDeniedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Zugriff verwehrt ähnelt.
        /// </summary>
        public static string AccessDeniedTitle {
            get {
                return ResourceManager.GetString("AccessDeniedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auf dem Android Gerät muss das USB-Debugging zugelassen werden, damit eine Verbindung hergestellt werden kann. ähnelt.
        /// </summary>
        public static string AdbAuthorization {
            get {
                return ResourceManager.GetString("AdbAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Android Gerät wurde gefunden, reagiert aber nicht. Bitte verbinde das USB-Kabel neu. ähnelt.
        /// </summary>
        public static string AdbOffline {
            get {
                return ResourceManager.GetString("AdbOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hinzufügen ähnelt.
        /// </summary>
        public static string AddButtonText {
            get {
                return ResourceManager.GetString("AddButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bitte starte {0} auch auf dem Gerät, das du koppeln möchtest und wähle es dann hier aus. ähnelt.
        /// </summary>
        public static string AddDeviceDialogIntro {
            get {
                return ResourceManager.GetString("AddDeviceDialogIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Koppelung mit dem Gerät &quot;{0}&quot; wurde erfolgreich hergestellt und kann nun genutzt werden. ähnelt.
        /// </summary>
        public static string AddDeviceDialogPairedMessage {
            get {
                return ResourceManager.GetString("AddDeviceDialogPairedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Die Koppelung wurde auf dem Gerät &quot;{0}&quot; abgelehnt. ähnelt.
        /// </summary>
        public static string AddDeviceDialogRejectedMessage {
            get {
                return ResourceManager.GetString("AddDeviceDialogRejectedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neues Gerät koppeln ähnelt.
        /// </summary>
        public static string AddDeviceDialogTitle {
            get {
                return ResourceManager.GetString("AddDeviceDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Der Bluetooth Adapter auf diesem Gerät ist nicht eingeschaltet. ähnelt.
        /// </summary>
        public static string BluetoothAdapterNotEnabled {
            get {
                return ResourceManager.GetString("BluetoothAdapterNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Empfang von Rfcomm Diensten vom Bluetooth Gerät {0} ist fehlgeschlagen: {1} ähnelt.
        /// </summary>
        public static string BluetoothRfcommServicesNotReceived {
            get {
                return ResourceManager.GetString("BluetoothRfcommServicesNotReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schließen ähnelt.
        /// </summary>
        public static string CloseButtonText {
            get {
                return ResourceManager.GetString("CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Gerät &quot;{0}&quot; ist nicht erreichtbar. ähnelt.
        /// </summary>
        public static string CommandSendFailure {
            get {
                return ResourceManager.GetString("CommandSendFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gerät ähnelt.
        /// </summary>
        public static string Device {
            get {
                return ResourceManager.GetString("Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Geräte ähnelt.
        /// </summary>
        public static string MenuDevices {
            get {
                return ResourceManager.GetString("MenuDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        public static string MenuSettings {
            get {
                return ResourceManager.GetString("MenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ansicht ähnelt.
        /// </summary>
        public static string MenuViewText {
            get {
                return ResourceManager.GetString("MenuViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bestätigung ähnelt.
        /// </summary>
        public static string MessageBoxTitleConfirmation {
            get {
                return ResourceManager.GetString("MessageBoxTitleConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler ähnelt.
        /// </summary>
        public static string MessageBoxTitleError {
            get {
                return ResourceManager.GetString("MessageBoxTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Information ähnelt.
        /// </summary>
        public static string MessageBoxTitleInformation {
            get {
                return ResourceManager.GetString("MessageBoxTitleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frage ähnelt.
        /// </summary>
        public static string MessageBoxTitleQuestion {
            get {
                return ResourceManager.GetString("MessageBoxTitleQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fehler auf dem Gerät &quot;{0}&quot; ähnelt.
        /// </summary>
        public static string MessageBoxTitleRemoteError {
            get {
                return ResourceManager.GetString("MessageBoxTitleRemoteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benachrichtigungen von diesem Gerät. ähnelt.
        /// </summary>
        public static string NotificationChannelLocalDescription {
            get {
                return ResourceManager.GetString("NotificationChannelLocalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lokale Benachrichtigungen ähnelt.
        /// </summary>
        public static string NotificationChannelLocalName {
            get {
                return ResourceManager.GetString("NotificationChannelLocalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benachrichtigungen zu Netzwerk-Problemen. ähnelt.
        /// </summary>
        public static string NotificationChannelNetworkDescription {
            get {
                return ResourceManager.GetString("NotificationChannelNetworkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Netzwerk ähnelt.
        /// </summary>
        public static string NotificationChannelNetworkName {
            get {
                return ResourceManager.GetString("NotificationChannelNetworkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benachrichtigungen zur Koppelung von Geräten. ähnelt.
        /// </summary>
        public static string NotificationChannelPairDescription {
            get {
                return ResourceManager.GetString("NotificationChannelPairDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Koppelungen ähnelt.
        /// </summary>
        public static string NotificationChannelPairName {
            get {
                return ResourceManager.GetString("NotificationChannelPairName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benachrichtigung über die Fernsteuerung dieses Gerätes ähnelt.
        /// </summary>
        public static string NotificationChannelRemoteControlDescription {
            get {
                return ResourceManager.GetString("NotificationChannelRemoteControlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fernsteuerung ähnelt.
        /// </summary>
        public static string NotificationChannelRemoteControlName {
            get {
                return ResourceManager.GetString("NotificationChannelRemoteControlName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Benachrichtigung vom Gerät &quot;{0}&quot;. ähnelt.
        /// </summary>
        public static string NotificationChannelRemoteDescription {
            get {
                return ResourceManager.GetString("NotificationChannelRemoteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} ähnelt.
        /// </summary>
        public static string NotificationChannelRemoteName {
            get {
                return ResourceManager.GetString("NotificationChannelRemoteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ok ähnelt.
        /// </summary>
        public static string OkButtonText {
            get {
                return ResourceManager.GetString("OkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vom Gerät &quot;{0}&quot; wurde eine Koppelungsanfrage gestellt. Soll dieses Gerät mit ihm gekoppelt werden? ähnelt.
        /// </summary>
        public static string PairAffectorDialogMessage {
            get {
                return ResourceManager.GetString("PairAffectorDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Koppeln ähnelt.
        /// </summary>
        public static string PairButtonText {
            get {
                return ResourceManager.GetString("PairButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gerät koppeln ähnelt.
        /// </summary>
        public static string PairDialogTitle {
            get {
                return ResourceManager.GetString("PairDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auf dem Gerät &quot;{0}&quot; wird jetzt eine Benachrichtigung angezeigt. Bitte bestätige in ihr die Koppelung. ähnelt.
        /// </summary>
        public static string PairInitiatorDialogMessage {
            get {
                return ResourceManager.GetString("PairInitiatorDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Soll das Gerät mit diesem gekoppelt werden? ähnelt.
        /// </summary>
        public static string PairNotificationMessage {
            get {
                return ResourceManager.GetString("PairNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Koppelungsanfrage von &quot;{0}&quot; ähnelt.
        /// </summary>
        public static string PairNotificationTitle {
            get {
                return ResourceManager.GetString("PairNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ablehnen ähnelt.
        /// </summary>
        public static string RejectButtonText {
            get {
                return ResourceManager.GetString("RejectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fernsteuerung ähnelt.
        /// </summary>
        public static string RemoteControl {
            get {
                return ResourceManager.GetString("RemoteControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Gerät muss erneut gekoppelt werden. ähnelt.
        /// </summary>
        public static string RemoteDeviceUnpaired {
            get {
                return ResourceManager.GetString("RemoteDeviceUnpaired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ein anderes Geräte hat vollen Zugriff auf dieses Gerät ähnelt.
        /// </summary>
        public static string ScreenshotServiceNotificationMessage {
            get {
                return ResourceManager.GetString("ScreenshotServiceNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dieses Geräte wird ferngesteuert ähnelt.
        /// </summary>
        public static string ScreenshotServiceNotificationTitle {
            get {
                return ResourceManager.GetString("ScreenshotServiceNotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Beenden ähnelt.
        /// </summary>
        public static string StopButtonText {
            get {
                return ResourceManager.GetString("StopButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entkoppeln ähnelt.
        /// </summary>
        public static string UnpairDevice {
            get {
                return ResourceManager.GetString("UnpairDevice", resourceCulture);
            }
        }
    }
}
