//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandaab.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sandaab.Core.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die adb.exe execution failed (Error: {0}) ähnelt.
        /// </summary>
        public static string AdbExecutionFailure {
            get {
                return ResourceManager.GetString("AdbExecutionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remote device at {0} cannot be connected. (Error: {1}) ähnelt.
        /// </summary>
        public static string ConnectFailure {
            get {
                return ResourceManager.GetString("ConnectFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The connection {0} was lost. (Error: {1}) ähnelt.
        /// </summary>
        public static string ConnectionLost {
            get {
                return ResourceManager.GetString("ConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error opening the file \&quot;{0}\&quot; ({1}). ähnelt.
        /// </summary>
        public static string FileOpen {
            get {
                return ResourceManager.GetString("FileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only {0} of {1} bytes are received. ähnelt.
        /// </summary>
        public static string IncompleteReceive {
            get {
                return ResourceManager.GetString("IncompleteReceive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only {0} of {1} bytes are sent. ähnelt.
        /// </summary>
        public static string IncompleteSent {
            get {
                return ResourceManager.GetString("IncompleteSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid adb.exe result (&quot;{0}&quot;). ähnelt.
        /// </summary>
        public static string InvalidAdbResult {
            get {
                return ResourceManager.GetString("InvalidAdbResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remote host app is not {0}. ähnelt.
        /// </summary>
        public static string InvalidListener {
            get {
                return ResourceManager.GetString("InvalidListener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} (Error: {1}) ähnelt.
        /// </summary>
        public static string IOException {
            get {
                return ResourceManager.GetString("IOException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot listen to {0} at port {1} (Error: {2}) ähnelt.
        /// </summary>
        public static string ListenError {
            get {
                return ResourceManager.GetString("ListenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} {1} ähnelt.
        /// </summary>
        public static string LogStart {
            get {
                return ResourceManager.GetString("LogStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} terminated normally ähnelt.
        /// </summary>
        public static string LogStop {
            get {
                return ResourceManager.GetString("LogStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Missing result from adb.exe. ähnelt.
        /// </summary>
        public static string MissingAdbResult {
            get {
                return ResourceManager.GetString("MissingAdbResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Multicast address {0} was not reachable (SocketError: {1}) ähnelt.
        /// </summary>
        public static string MulticastAddressUnreachable {
            get {
                return ResourceManager.GetString("MulticastAddressUnreachable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The system notifications are disabled (Reson: {0}) ähnelt.
        /// </summary>
        public static string NoticationDisabled {
            get {
                return ResourceManager.GetString("NoticationDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connect request with obsolete access token from {0} ähnelt.
        /// </summary>
        public static string ObsoleteAccessToken {
            get {
                return ResourceManager.GetString("ObsoleteAccessToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} (SocketError: {1}) ähnelt.
        /// </summary>
        public static string SocketError {
            get {
                return ResourceManager.GetString("SocketError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die USB device &quot;{0}&quot; is used by an other App. ähnelt.
        /// </summary>
        public static string UsbDeviceAccessDenied {
            get {
                return ResourceManager.GetString("UsbDeviceAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} (Error: {1}) ähnelt.
        /// </summary>
        public static string Win32Error {
            get {
                return ResourceManager.GetString("Win32Error", resourceCulture);
            }
        }
    }
}
